data:
  augmentation:
    center_crop: true
    center_crop_ratio: 0.9
model:
  diffusion_steps: 5
  scheduler_type: "flow_match"
  attn_implementation: "sdpa"
eval:
  finetuned_checkpoint: "/mnt/afs-h200/yuyangcheng/workplace/VLANeXt/VLANeXt_ablation_wm/ttt_chunk256_libero_object/checkpoint_final.pt"
  task_suite_name: "libero_object"
  task_ids: [659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704]
  shard_tag: "envgen_objcam_s123b_shard0"
  num_steps_wait: 10
  num_steps_execute: 8
  num_trials_per_task: 1
  seed: 123
  image_size: 256
  resume_episodes: 0
  resume_successes: 0
