data:
  augmentation:
    center_crop: true
    center_crop_ratio: 0.9
model:
  diffusion_steps: 5
  scheduler_type: "flow_match"
  attn_implementation: "sdpa"
eval:
  finetuned_checkpoint: "/mnt/afs-h200/yuyangcheng/workplace/VLANeXt/VLANeXt_ablation_wm/ttt_chunk256_libero_object/checkpoint_final.pt"
  task_suite_name: "libero_object"
  task_ids: [806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851]
  shard_tag: "envgen_objcam_s123b_shard3"
  num_steps_wait: 10
  num_steps_execute: 8
  num_trials_per_task: 1
  seed: 123
  image_size: 256
  resume_episodes: 0
  resume_successes: 0
