data:
  augmentation:
    center_crop: true
    center_crop_ratio: 0.9
model:
  diffusion_steps: 5
  scheduler_type: "flow_match"
  attn_implementation: "sdpa"
eval:
  finetuned_checkpoint: "/mnt/afs-h200/yuyangcheng/workplace/VLANeXt/VLANeXt_ablation_wm/ttt_chunk256_libero_object/checkpoint_final.pt"
  task_suite_name: "libero_object"
  task_ids: [898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953]
  shard_tag: "envgen_objcam_s123b_shard5"
  num_steps_wait: 10
  num_steps_execute: 8
  num_trials_per_task: 1
  seed: 123
  image_size: 256
  resume_episodes: 0
  resume_successes: 0
